#!/usr/bin/env ruby

require "rredis"
require "socket"

engine = RRedis::Engine.new

Socket.tcp_server_loop(6379) do |connection|
  Thread.new do
    RRedis::Connection.connect(engine, connection)
  end
end
